### ISSUE TITLE
Download fails during unpad function

### ISSUE THREAD

**Issue by manzari** [nlscc/samloader#1]
Hello,
I was very amazed as I found your efforts to provide an alternative to samfirm!

Howerver while downloading with the exact command in the readme the lambda function `unpad = lambda d: d[:-d[-1]]` in line 13 of `auth.py` throws the following stack trace and error. 

```
Traceback (most recent call last):
  File "/home/user/projects/samloader/venv/bin/samloader", line 11, in <module>
    load_entry_point('samloader', 'console_scripts', 'samloader')()
  File "/usr/local/lib/python2.7/dist-packages/click-7.1.2-py2.7.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-7.1.2-py2.7.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-7.1.2-py2.7.egg/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-7.1.2-py2.7.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-7.1.2-py2.7.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/projects/samloader/samloader/main.py", line 43, in download
    client = fusclient.FUSClient()
  File "/home/user/projects/samloader/samloader/fusclient.py", line 14, in __init__
    self.makereq("NF_DownloadGenerateNonce.do")
  File "/home/user/projects/samloader/samloader/fusclient.py", line 21, in makereq
    self.nonce = auth.decryptnonce(self.encnonce)
  File "/home/user/projects/samloader/samloader/auth.py", line 39, in decryptnonce
    nonce = aes_decrypt(base64.b64decode(inp), KEY_1.encode()).decode()
  File "/home/user/projects/samloader/samloader/auth.py", line 23, in aes_decrypt
    unpadded_cipher = unpad(decrypted_cipher)
  File "/home/user/projects/samloader/samloader/auth.py", line 13, in <lambda>
    unpad = lambda d: d[:-d[-1]]
TypeError: bad operand type for unary -: 'str'

Process finished with exit code 1
```
I tried to come up with a fix for this issue but everything I try, like `unpad = lambda d: d.rstrip(d[-1])`, ends in a 401 response from kies servers.

Any help is appreciated and any explanation also. If you cant reproduce the error, please just let me know what this line is intended to do so I can fix it for myself and provide a PR if you like.

**Comment by nlscc** [comment]
Hello,
You seem to be using python2.7. This version of python isn't supported, please use python3 instead.
This function is doing a PKCS7 unpad (for the encryption). The reason this doesn't work is that there is no bytes in python2, so indexing it like that will return string instead of int. But apart from that, there are a lot of python3 features used that will function properly with python2.
If you can still reproduce the issue using the latest python version, please let me know.
