### ISSUE TITLE
Download issues when trying to load firmware

### ISSUE THREAD

**Issue by Tkkg1994** [nlscc/samloader#12]
Hey, thanks for your tool, good work on this one!

I want to share an issue with you, when you try to load the firmware SM-R820. It works fine to check the latest firmware and you can check various CSC variants it works fine.

But then when you enter the same firmware to download, an issue appears. Here below I posted the output of the cmd. Thanks for having a look!
You can easily replicate the issue.

Also to note, on other variants like the S10 or S20, the tool works superbe

`C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts>samloader download R820XXU1CTI4/R820OXA1CTI4/R820XXU1CTI4/R820XXU1CTI4 SM-R820 AUT .
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\samloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\samloader\main.py", line 45, in download
    path, filename = getbinaryfile(client, version, region, model)
  File "C:\Users\lucag\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\samloader\main.py", line 19, in getbinaryfile
    filename = root.find("./FUSBody/Put/BINARY_NAME/Data").text
AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by nlscc** [comment]
`SM-R820` seems to be a watch, there is no available firmware for smartwatches on the Samsung server. Currently when a firmware does not exist it throws that message, but see #9 about that issue

**Comment by Tkkg1994** [comment]
It would be helpful to add a message about that. Like "firmware not found" or "can't download file" something like this. So the user sees where the problem is, otherwise you get many more bug reports :)

Also, why does it find the firmware then when you can't download it?

**Comment by nlscc** [comment]
I have now (: see #9 6f8094c
The reason it can find the update but can't download it is because the list of latest updates is on a separate server used for OTA updates (I think) while the firmware images are on a server used by KIES / Smart Switch. It might be possible to use the same server but this is also how SamFirm did it.
