### ISSUE TITLE
Exception: DownloadBinaryInform returned 200, firmware could not be found?

### ISSUE THREAD

**Issue by dhananjaygbhardwaj** [nlscc/samloader#13]
## Description
I have successfully installed Python 3.8.6 and Samloader on my machine. Upon executing "checkupdate", Samloader does return the firmware version. However, when further executing the download command, it fails with "Exception: DownloadBinaryInform returned 200, firmware could not be found?" error. Full output below.

```
dhananjay@Dhananjays-MacBook-Air ~ % samloader checkupdate SM-G965F INS
G965FXXSBETH2/G965FOXMBETG8/G965FXXSBETH2/G965FXXSBETH2

dhananjay@Dhananjays-MacBook-Air ~ % samloader download G965FXXSBETH2/G965FOXMBETG8/G965FXXSBETH2/G965FXXSBETH2 SM-G965F INS .
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/samloader", line 33, in <module>
    sys.exit(load_entry_point('samloader==0.1', 'console_scripts', 'samloader')())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samloader/main.py", line 48, in download
    path, filename = getbinaryfile(client, version, region, model)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samloader/main.py", line 21, in getbinaryfile
    raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
Exception: DownloadBinaryInform returned 200, firmware could not be found?
```
The same error is returned when I tried on my Windows 10 computer.

## Environment
Windows 10, macOS 10.15.6, and Python 3.8.6

**Comment by nlscc** [comment]
Should be fixed now, probably should have tested better lol
