### ISSUE TITLE
Firmware download error - Exception: DownloadBinaryInform returned 400, firmware could not be found?

### ISSUE THREAD

**Issue by ajeeth1291** [nlscc/samloader#25]
## Description
Unable to download firmware for a specific device - SM-R805F. Download worked on a different model.

## Reproduction Steps

$ python3 -m samloader -m SM-R805F -r INU checkupdate
R805FXXU1FTC1/R805FOXX1FTC1/R805FXXU1FTC1/R805FXXU1FTC1

$ python3 -m samloader -m SM-R805F -r INU download -v R805FXXU1FTC1/R805FOXX1FTC1/R805FXXU1FTC1/R805FXXU1FTC1 -O .

## Output
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/demo/.local/lib/python3.7/site-packages/samloader/__main__.py", line 6, in <module>
    main()
  File "/home/demo/.local/lib/python3.7/site-packages/samloader/main.py", line 36, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
  File "/home/demo/.local/lib/python3.7/site-packages/samloader/main.py", line 74, in getbinaryfile
    raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
Exception: DownloadBinaryInform returned 400, firmware could not be found?

## Environment
Python 3.7 on MX Linux 19.2

**Comment by nlscc** [comment]
'SM-R805F' is a watch, sadly Samsung doesn't store the factory firmware files for watches (as far as I know), meaning that it can detect an update but not download it. This is why the tool prints a 'firmware could not be found' error.

**Comment by ajeeth1291** [comment]
I didn't realize a similar issue was already commented on by you, thanks for the response.
