### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by slangda** [nlscc/samloader#3]
Python 3.8.3

Traceback (most recent call last):
  File "/usr/bin/samloader", line 33, in <module>
    sys.exit(load_entry_point('samloader==0.1', 'console_scripts', 'samloader')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/samloader/main.py", line 46, in download
    path, filename = getbinaryfile(client, version, region, model)
  File "/usr/lib/python3.8/site-packages/samloader/main.py", line 20, in getbinaryfile
    filename = root.find("./FUSBody/Put/BINARY_NAME/Data").text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by nlscc** [comment]
Could you send what command you ran to trigger this error so I can try to reproduce it?

**Comment by slangda** [comment]
samloader T720XXU1BTF7/T720OXM1BTF7/T720XXU1BTF7 SM-T720 PHN image.zip.enc2

just checked in another tool and it goes for enc4, maybe enc2 was removed from the source?

**Comment by nlscc** [comment]
OK, so I think I found the issue.
For now, try this instead:
```
samloader download T720XXU1BTF7/T720OXM1BTF7/T720XXU1BTF7/T720XXU1BTF7 SM-T720 PHN image.zip.enc4
```
