### ISSUE TITLE
getlogiccheck() input too short

### ISSUE THREAD

**Issue by ObscenityIB** [nlscc/samloader#30]
## Description
Downloading fails

## Reproduction Steps
`samloader -m SM-G988B -r XSA download -v G988BXXU5BTJ3 -o here`

## Output
```
Traceback (most recent call last):
  File "c:\users\user name\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user name\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User Name\AppData\Local\Programs\Python\Python39\Scripts\samloader.exe\__main__.py", line 7, in <module>
  File "c:\users\user name\appdata\local\programs\python\python39\lib\site-packages\samloader\main.py", line 36, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
  File "c:\users\user name\appdata\local\programs\python\python39\lib\site-packages\samloader\main.py", line 69, in getbinaryfile
    req = request.binaryinform(fw, model, region, client.nonce)
  File "c:\users\user name\appdata\local\programs\python\python39\lib\site-packages\samloader\request.py", line 28, in binaryinform
    ET.SubElement(ET.SubElement(fput, "LOGIC_CHECK"), "Data").text = getlogiccheck(fw, nonce)
  File "c:\users\user name\appdata\local\programs\python\python39\lib\site-packages\samloader\request.py", line 10, in getlogiccheck
    raise Exception("getlogiccheck() input too short")
Exception: getlogiccheck() input too short
```

## Environment
`Microsoft Windows [Version 10.0.19042.630]`
`Python 3.9.0`

**Comment by luk1337** [comment]
Run `samloader -m SM-G988B -r XSA checkupdate` and then pass the whole output in `-v` parameter when trying to download the firmware.

**Comment by ObscenityIB** [comment]
@luk1337 are these not separate versions?

**Comment by luk1337** [comment]
that's the combination of pda/csc/modem that you're supposed to pass as is.

**Comment by ObscenityIB** [comment]
ah, so what if i want `G988BXXU1ATBK`
which isnt listed
would it work if i make the same kind of formatting?

**Comment by luk1337** [comment]
I don't think you can download anything but the latest FW.

**Comment by ObscenityIB** [comment]
i tried it
worked, which is pretty cool
`G988BXXU1ATBK/G988BOXM1ATBL/G988BXXU1ATBP/G988BXXU1ATBK`

closing this issue anyways
perhaps need some kind of catch for this specific misuse
