### ISSUE TITLE
Failing to download firmware

### ISSUE THREAD

**Issue by androidian5980** [nlscc/samloader#31]
## Description
I'm trying to download the latest XAC firmware for my A520W but it always fails

## Reproduction Steps
1. Install samloader normally 2. Try and download the firmware 3. It fails 4. Sadness

## Output
andrew@thinkpad:~
$ python3 -m samloader -m SM-A520W -r XAC download -v A520WVLSECTJ1/A520WOYAECTJ1/A520WVLSECTJ1/A520WVLSECTJ1 -o .
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/andrew/.local/lib/python3.7/site-packages/samloader/__main__.py", line 6, in <module>
    main()
  File "/home/andrew/.local/lib/python3.7/site-packages/samloader/main.py", line 36, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
  File "/home/andrew/.local/lib/python3.7/site-packages/samloader/main.py", line 74, in getbinaryfile
    raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
Exception: DownloadBinaryInform returned 400, firmware could not be found?
andrew@thinkpad:~
$

## Environment
Debian 10 Buster x64, Thinkpad T410, Python 3.7.3, Pip3 18.1

**Comment by nlscc** [comment]
Works for me (except `-o` should be `-O`), perhaps when you were doing this the firmware was not yet uploaded to the Samsung server? It sometimes can take a few days for it to become available. Can you try doing this again now?
