### ISSUE TITLE
Downloading starts but fails, HTTPError: 405

### ISSUE THREAD

**Issue by m4nnerheim** [nlscc/samloader#32]
## Description

When starting a download it instantly fails. It manages however to create 1 item before it fails.

## Reproduction Steps

`$ samloader -m SM-G970F -r NEE checkupdate`
`G970FXXU9DTJA/G970FOXM9DTJB/G970FXXU9DTJA/G970FXXU9DTJA`

`samloader -m SM-G970F -r NEE download -v G970FXXU9DTJA/G970FOXM9DTJB/G970FXXU9DTJA/G970FXXU9DTJA -O .`

## Output

```python
downloading SM-G970F_1_20201028044204_tm4iurcth4_fac.zip.enc4
Traceback (most recent call last):
  File "/home/user/.local/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/samloader/main.py", line 45, in main
    r = client.downloadfile(path+filename, dloffset)
  File "/home/user/.local/lib/python3.8/site-packages/samloader/fusclient.py", line 35, in downloadfile
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://cloud-neofussvr.sslcs.cdngc.net/NF_DownloadBinaryForMass.do?file=%2Fneofus%2F910%2FSM-G970F_1_20201028044204_tm4iurcth4_fac.zip.enc4
```

## Environment

Linux / Pop!_OS 20.10
Python 3.8.6

**Comment by m4nnerheim** [comment]
If it wasn't clear, the `SM-G970F_1_20201028044204_tm4iurcth4_fac.zip.enc4` file was created in this case. My filemanager says it's 0 bytes so can't imagine it's anything worth decrypting.

**Comment by mijofa** [comment]
I'm getting the same with a different device, I've not used this tool before so I'm not entirely certain I'm using it right, but it doesn't seem like my fault

```
$ python3 -m samloader --dev-model SM-T720 --dev-region XAR checkupdate
T720XXU1CTK1/T720OXM1CTK1/T720XXU1CTK1/T720XXU1CTK1

$ python3 -m samloader --dev-model SM-T720 --dev-region XAR download --fw-ver T720XXU1CTK1/T720OXM1CTK1/T720XXU1CTK1/T720XXU1CTK1 --out-dir .
downloading SM-T720_1_20201113161133_p0du3fp52e_fac.zip.enc4
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mike/.local/lib/python3.7/site-packages/samloader/__main__.py", line 6, in <module>
    main()
  File "/home/mike/.local/lib/python3.7/site-packages/samloader/main.py", line 45, in main
    r = client.downloadfile(path+filename, dloffset)
  File "/home/mike/.local/lib/python3.7/site-packages/samloader/fusclient.py", line 35, in downloadfile
    r.raise_for_status()
  File "/home/mike/.local/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: http://cloud-neofussvr.sslcs.cdngc.net/NF_DownloadBinaryForMass.do?file=%2Fneofus%2F910%2FSM-T720_1_20201113161133_p0du3fp52e_fac.zip.enc4
```

**Comment by mijofa** [comment]
Have confirmed, that works for me. Thank you! :+1:
