### ISSUE TITLE
Implement Manual Mode as in Frija

### ISSUE THREAD

**Issue by sherpya** [nlscc/samloader#34]
## Description
I was searching for an old firmware for an old firmware:

https://samfrew.com/it/download/Galaxy__Young__/9w83/ITV/S6310NXXAMD2/S6310NOXXAMD3/

Frija (Auto Modo) and samloader are unable to find that file

But Frija can in manual mode, by specifying PDA CSC and Phone

It would be nice to have same option

**Comment by ianmacd** [comment]
`samloader` has this. Just specify the correct version string with `-v`.

For example:

`samloader -m SM-N986B -r PHN download -v N986BXXS1ATJA/N986BOXM1ATJ1/N986BXXU1ATJ5/N986BXXS1ATJA -o foo.enc4`

That's not the latest version for the N986B, but the above command will download it.

**Comment by sherpya** [comment]
```
samloader -m GT-S6310N -r ITV checkupdate
Traceback (most recent call last):
  File "/tmp/v/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/tmp/v/lib/python3.9/site-packages/samloader/main.py", line 55, in main
    print(versionfetch.getlatestver(args.dev_model, args.dev_region))
  File "/tmp/v/lib/python3.9/site-packages/samloader/versionfetch.py", line 15, in getlatestver
    raise Exception("No latest firmware found")
Exception: No latest firmware found
```
Actually I known the versions but I don't understand samloader syntax

https://samfrew.com/it/download/Galaxy__Young__/9w83/ITV/S6310NXXAMD2/S6310NOXXAMD3/

tried without success:

- S6310NXXAMD2/S6310NOXXAMD3/S6310NXXAMD3
- S6310NOXXAMD3/S6310NXXAMD3/S6310NXXAMD2
- S6310NXXAMD3/S6310NXXAMD2/S6310NOXXAMD3
- S6310NOXXAMD3/S6310NXXAMD2/S6310NXXAMD3
- S6310NXXAMD2/S6310NXXAMD3/S6310NOXXAMD3
- S6310NXXAMD3/S6310NOXXAMD3/S6310NXXAMD2

I suppose the problems is https://fota-cloud-dn.ospserver.net/firmware/ITV/GT-S6310N/version.xml has no firmwares
looks like the version syntax is PDA/CSC/MODEM so `S6310NXXAMD2/S6310NOXXAMD3/S6310NXXAMD3` should work

here frija manual mode screenshot:
![frija](https://user-images.githubusercontent.com/120074/103493197-143ef880-4e30-11eb-9eb1-304cb4aa8804.png)

**Comment by sherpya** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<FUSMsg>
	<FUSHdr>
		<ProtoVer>1.0</ProtoVer>
		<SessionID></SessionID>
		<MsgID>2</MsgID>
	</FUSHdr>
	<FUSBody>
		<Results>
			<CmdRef>2</CmdRef>
			<Status>200</Status>
			<LATEST_FW_VERSION>
				<Data>S6310NXXAMD2/S6310NOXXAMD3/S6310NXXAMD3/S6310NXXAMD2</Data>
			</LATEST_FW_VERSION>
		</Results>
		<Put>
			<CmdID>1</CmdID>
			<BINARY_CRC>
				<Data> </Data>
			</BINARY_CRC>
			<BINARY_NAME>
				<Data></Data>
			</BINARY_NAME>
			<BINARY_SIZE>
				<Data>0</Data>
			</BINARY_SIZE>
			<BINARY_BYTE_SIZE>
				<Data></Data>
			</BINARY_BYTE_SIZE>
			<DESCRIPTION>
				<Data></Data>
			</DESCRIPTION>
			<DESCRIPTION_FLAG>
				<Data>0</Data>
			</DESCRIPTION_FLAG>
			<SUPPORT_HIDDEN>
				<Data>0</Data>
			</SUPPORT_HIDDEN>
			<FW_INDEX>
				<Data>1</Data>
			</FW_INDEX>
			<DEVICE_MODEL_NAME>
				<Data>GT-S6310N</Data>
			</DEVICE_MODEL_NAME>
			<DEVICE_MODEL_TYPE>
				<Data>9</Data>
			</DEVICE_MODEL_TYPE>
			<MODEL_PATH>
				<Data>/neofus/9/</Data>
			</MODEL_PATH>
			<DEVICE_BUYER_CODE>
				<Data>XX</Data>
			</DEVICE_BUYER_CODE>
			<DEVICE_LOCAL_CODE>
				<Data>ITV</Data>
			</DEVICE_LOCAL_CODE>
			<ANNOUNCE_FLAG>
				<Data>0</Data>
			</ANNOUNCE_FLAG>
			<ANNOUNCE>
				<Data></Data>
			</ANNOUNCE>
			<NOTIFY>
				<Data>1</Data>
			</NOTIFY>
			<LAST_MODIFIED>
				<Data>20130502135521</Data>
			</LAST_MODIFIED>
			<DEVICE_PLATFORM>
				<Data>Android</Data>
			</DEVICE_PLATFORM>
			<PLATFORM_SUPPORT>
				<Data>0</Data>
			</PLATFORM_SUPPORT>
			<DEVICE_BOOT_FILE>
				<Data></Data>
			</DEVICE_BOOT_FILE>
			<DEVICE_PDA_CODE1_FILE>
				<Data></Data>
			</DEVICE_PDA_CODE1_FILE>
			<DEVICE_CSC_CODE2_FILE>
				<Data></Data>
			</DEVICE_CSC_CODE2_FILE>
			<DEVICE_PHONE_FONT_FILE>
				<Data></Data>
			</DEVICE_PHONE_FONT_FILE>
			<DEVICE_CONTENTS_DATA_FILE>
				<Data></Data>
			</DEVICE_CONTENTS_DATA_FILE>
			<DEVICE_LANGUAGE_FILE>
				<Data></Data>
			</DEVICE_LANGUAGE_FILE>
			<DEVICE_BINARY_FOLDER>
				<Data></Data>
			</DEVICE_BINARY_FOLDER>
			<DEVICE_AMSS_FILE>
				<Data></Data>
			</DEVICE_AMSS_FILE>
			<DEVICE_RSRC1_FILE>
				<Data></Data>
			</DEVICE_RSRC1_FILE>
			<DEVICE_RSRC2_FILE>
				<Data></Data>
			</DEVICE_RSRC2_FILE>
			<DEVICE_CSC_FILE>
				<Data></Data>
			</DEVICE_CSC_FILE>
			<DEVICE_X_FS_FILE>
				<Data></Data>
			</DEVICE_X_FS_FILE>
			<DEVICE_APPS_FILE>
				<Data></Data>
			</DEVICE_APPS_FILE>
			<DEVICE_SHPAPP_FILE>
				<Data></Data>
			</DEVICE_SHPAPP_FILE>
			<DEVICE_FOTA_FILE>
				<Data></Data>
			</DEVICE_FOTA_FILE>
			<DEVICE_PFS_FILE>
				<Data></Data>
			</DEVICE_PFS_FILE>
			<DEVICE_PFS_SIZE>
				<Data></Data>
			</DEVICE_PFS_SIZE>			
			<DEVICE_BSY_FILE>
				<Data></Data>
			</DEVICE_BSY_FILE>
			<DEVICE_CDS_FILE>
				<Data></Data>
			</DEVICE_CDS_FILE>
			<DEVICE_UIIMAGE_FILE>
				<Data></Data>
			</DEVICE_UIIMAGE_FILE>
			<DEVICE_PSIFLASH_FILE>
				<Data></Data>
			</DEVICE_PSIFLASH_FILE>
			<DEVICE_INI_FILE>
				<Data></Data>
			</DEVICE_INI_FILE>
			<DEVICE_DSP1_FILE>
				<DATA></DATA>
			</DEVICE_DSP1_FILE>
			<DEVICE_DSP2_FILE>
				<DATA></DATA>
			</DEVICE_DSP2_FILE>
			<DEVICE_EFS_FILE>
				<DATA></DATA>
			</DEVICE_EFS_FILE>
			<DEVICE_BOOT_ADDRESS>
				<Data></Data>
			</DEVICE_BOOT_ADDRESS>
			<DEVICE_CODE1_ADDRESS>
				<Data></Data>
			</DEVICE_CODE1_ADDRESS>
			<DEVICE_CODE2_ADDRESS>
				<Data></Data>
			</DEVICE_CODE2_ADDRESS>
			<DEVICE_FONT_ADDRESS>
				<Data></Data>
			</DEVICE_FONT_ADDRESS>
			<DEVICE_DATA_ADDRESS>
				<Data></Data>
			</DEVICE_DATA_ADDRESS>
			<DEVICE_VIA_BOOT_FILE>
				<Data></Data>
			</DEVICE_VIA_BOOT_FILE>
			<DEVICE_VIA_CODE_FILE>
				<Data></Data>
			</DEVICE_VIA_CODE_FILE>
			<DEVICE_PIT_FILE>
				<Data></Data>
			</DEVICE_PIT_FILE>
			<CURRENT_DISPLAY_VERSION>
				<Data>S6310NXXAMD2/S6310NOXXAMD3/S6310NXXAMD3/S6310NXXAMD2</Data>
			</CURRENT_DISPLAY_VERSION>
			<LATEST_DISPLAY_VERSION>
				<Data>S6310NXXAMD2/S6310NOXXAMD3/S6310NXXAMD3/S6310NXXAMD2</Data>
			</LATEST_DISPLAY_VERSION>
			<CASH_SERVER_IP>
				<Data></Data>
			</CASH_SERVER_IP>
			<BLOCKING_APP>
				<Data>0</Data>
			</BLOCKING_APP>
			<BINARY_EMERGENCY_OTP_RECEIVE>
				<Data></Data>
			</BINARY_EMERGENCY_OTP_RECEIVE>
			<DEVICE_IMEI_NUMBER>
				<Data></Data>
			</DEVICE_IMEI_NUMBER>
			<UPDATE_NOTICE>
				<Data>0</Data>
			</UPDATE_NOTICE>
			<BINARY_TYPE>
				<Data>0</Data>
			</BINARY_TYPE>
			<SUPPORT_BD_20>
				<Data>0</Data>
			</SUPPORT_BD_20>
			<BINARY_CRC_BD_20>
				<Data></Data>
			</BINARY_CRC_BD_20>
			<BINARY_SIZE_BD_20>
				<Data></Data>
			</BINARY_SIZE_BD_20>
			<BINARY_NAME_BD_20>
				<Data></Data>
			</BINARY_NAME_BD_20>
			<LAST_MODIFIED_BD_20>
				<Data></Data>
			</LAST_MODIFIED_BD_20>
			<DEVICE_BINARY_FOLDER_BD_20>
				<Data></Data>
			</DEVICE_BINARY_FOLDER_BD_20>
			<DEVICE_AMSS_FILE_BD_20>
				<Data></Data>
			</DEVICE_AMSS_FILE_BD_20>
			<DEVICE_RSRC1_FILE_BD_20>
				<Data></Data>
			</DEVICE_RSRC1_FILE_BD_20>
			<DEVICE_RSRC2_FILE_BD_20>
				<Data></Data>
			</DEVICE_RSRC2_FILE_BD_20>
			<DEVICE_X_FS_FILE_BD_20>
				<Data></Data>
			</DEVICE_X_FS_FILE_BD_20>
			<DEVICE_APPS_FILE_BD_20>
				<Data></Data>
			</DEVICE_APPS_FILE_BD_20>
			<DEVICE_CSC_FILE_BD_20>
				<Data></Data>
			</DEVICE_CSC_FILE_BD_20>
			<DEVICE_SHPAPP_FILE_BD_20>
				<Data></Data>
			</DEVICE_SHPAPP_FILE_BD_20>
			<DEVICE_FOTA_FILE_BD_20>
				<Data></Data>
			</DEVICE_FOTA_FILE_BD_20>
			<DEVICE_PFS_FILE_BD_20>
				<Data></Data>
			</DEVICE_PFS_FILE_BD_20>
			<DEVICE_PFS_SIZE_BD_20>
				<Data></Data>
			</DEVICE_PFS_SIZE_BD_20>
			<FW_INDEX_BD_20>
				<Data></Data>
			</FW_INDEX_BD_20>
			<LATEST_DISPLAY_VERSION_BD_20>
				<Data></Data>
			</LATEST_DISPLAY_VERSION_BD_20>
			<LATEST_FW_VERSION_BD_20>
				<Data></Data>
			</LATEST_FW_VERSION_BD_20>
			<BINARY_EMERGENCY_OTP_RECEIVE_BD_20>
				<Data></Data>
			</BINARY_EMERGENCY_OTP_RECEIVE_BD_20>
			<BNR_SUPPORT>
				<Data>0</Data>
			</BNR_SUPPORT>
			<CDNURL>
				<Data>https://neofussvr.sslcs.cdngc.net/</Data>
			</CDNURL>
			<DEVICE_MODEL_DISPLAYNAME>
				<Data>GALAXY YOUNG</Data>
			</DEVICE_MODEL_DISPLAYNAME>
			<FACTORY_SUPPORT>
				<Data>3</Data>
			</FACTORY_SUPPORT>
			<FACTORY_DO_EXIST>
				<Data>0</Data>
			</FACTORY_DO_EXIST>
			<BINARY_NATURE>
				<Data>1</Data>
			</BINARY_NATURE>
			<FACTORY_KEY_TYPE>
				<Data>6</Data>
			</FACTORY_KEY_TYPE>
			<NOTICE_URL_FIRST>
				<Data></Data>
			</NOTICE_URL_FIRST>
			<NOTICE_URL_LAST>
				<Data></Data>
			</NOTICE_URL_LAST>
			<MEMORY_SIZE_CHECK>
				<Data>3</Data>
			</MEMORY_SIZE_CHECK>
			<ROUTING_SUPPORT>
				<Data>0</Data>
			</ROUTING_SUPPORT>
			<SN_TYPE>
				<Data></Data>
			</SN_TYPE>
			<SETTING_INFO>
				<Data></Data>
			</SETTING_INFO>
			<MEMORY_ANNOUNCE>
				<Data></Data>
			</MEMORY_ANNOUNCE>
			<UPGRADE_VARIABLE>
				<Data>0</Data>
			</UPGRADE_VARIABLE>
			<BUTTON_TYPE>
				<Data>0</Data>
			</BUTTON_TYPE>
			<ADD_DESCRIPTION_FLAG>
				<Data>0</Data>
			</ADD_DESCRIPTION_FLAG>
			<ADD_DESCRIPTION>
				<Data></Data>
			</ADD_DESCRIPTION>
			<ADD_ANNOUNCE_FLAG>
				<Data>0</Data>
			</ADD_ANNOUNCE_FLAG>
			<ADD_ANNOUNCE>
				<Data></Data>
			</ADD_ANNOUNCE>
			<ADD_LATEST_DISPLAY_VERSION>
				<Data>S6310NXXAMD2/S6310NOXXAMD3/S6310NXXAMD3/S6310NXXAMD2</Data>
			</ADD_LATEST_DISPLAY_VERSION>
			<ADD_LATEST_FW_VERSION>
				<Data>S6310NXXAMD2/S6310NOXXAMD3/S6310NXXAMD3/S6310NXXAMD2</Data>
			</ADD_LATEST_FW_VERSION>
			<CURRENT_OS_VERSION>
				<Data>Jelly Bean(Android 4.1.2)</Data>
			</CURRENT_OS_VERSION>
			<LATEST_OS_VERSION>
				<Data>Jelly Bean(Android 4.1.2)</Data>
			</LATEST_OS_VERSION>
			<ADD_OS_VERSION>
				<Data>Jelly Bean(Android 4.1.2)</Data>
			</ADD_OS_VERSION>
			<ADD_NOTICE_URL_FIRST>
				<Data></Data>
			</ADD_NOTICE_URL_FIRST>
			<ADD_NOTICE_URL_LAST>
				<Data></Data>
			</ADD_NOTICE_URL_LAST>
			<OBEX_SUPPORT>
				<Data>0</Data>
			</OBEX_SUPPORT>
			<ABSOLUTE_SUPPORT>
				<Data>0</Data>
			</ABSOLUTE_SUPPORT>
			<COMMON_PLUGIN>
				<Data>0</Data>
			</COMMON_PLUGIN>
			<VERSION_HELP_TEXT>
				<Data>1</Data>
			</VERSION_HELP_TEXT>
			<LOGIC_OPTION_HOME>
				<Data>0</Data>
			</LOGIC_OPTION_HOME>
			<LOGIC_VALUE_HOME>
				<Data></Data>
			</LOGIC_VALUE_HOME>
			<LOGIC_OPTION_FACTORY>
				<Data>0</Data>
			</LOGIC_OPTION_FACTORY>
			<LOGIC_VALUE_FACTORY>
				<Data></Data>
			</LOGIC_VALUE_FACTORY>
			<CDN_TRAFFIC>
				<Data></Data>
			</CDN_TRAFFIC>
			<CDN_TRAFFIC_OPTION>
				<Data></Data>
			</CDN_TRAFFIC_OPTION>
			<BATTERY_STANDARDS>
				<Data></Data>
			</BATTERY_STANDARDS>
			<BATTERY_PERCENT>
				<Data></Data>
			</BATTERY_PERCENT>
			<SHARING_BINARY>
				<Data>0</Data>
			</SHARING_BINARY>
			<DEVICE_CSC_HOME_FILE>
				<Data></Data>
			</DEVICE_CSC_HOME_FILE>
			
			<USER_DATA_BINARY>
				<Data>0</Data>
			</USER_DATA_BINARY>
			<DEVICE_USER_DATA_FILE>
				<Data></Data>
			</DEVICE_USER_DATA_FILE>
			<DVIF_SALES_VER>
				<Data>0</Data>
			</DVIF_SALES_VER>
			<SIZE_CHECK_PATH>
				<Data>0</Data>
			</SIZE_CHECK_PATH>
			<SSP_DEVICE_SIZECHECK>
				<Data>0</Data>
			</SSP_DEVICE_SIZECHECK>
		</Put> 
	</FUSBody>
</FUSMsg>
```

**Comment by sherpya** [comment]
``xml
			<BINARY_BYTE_SIZE>
				<Data></Data>
			</BINARY_BYTE_SIZE>
```
is empty

**Comment by sherpya** [comment]
Frija add also `DEVICE_PDA_CODE1_VERSION`, `DEVICE_CSC_CODE2_VERSION`, `DEVICE_PHONE_FONT_VERSION` and `DEVICE_CONTENTS_DATA_VERSION` to the request, but I get same result even adding them, need to understand better what Frija does
