### ISSUE TITLE
Issue with retrieving update data

### ISSUE THREAD

**Issue by slangda** [nlscc/samloader#5]
I appreciate your efforts and code very much. Thank you for bringing this out in the open.

Python 3.8.5
samloader most recent version (30-7-2020)

samloader checkupdate SM-T720 PHY

Traceback (most recent call last):
  File "/usr/bin/samloader", line 33, in <module>
    sys.exit(load_entry_point('samloader==0.1', 'console_scripts', 'samloader')())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/samloader/main.py", line 34, in checkupdate
    fw = versionfetch.getlatestver(region, model)
  File "/usr/lib/python3.8/site-packages/samloader/versionfetch.py", line 12, in getlatestver
    vercode = root.find("./firmware/version/latest").text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by nlscc** [comment]
I don't think PHY is a valid region, could you recheck that? I can't find it on any lists of Samsung region codes and it works fine with others.

**Comment by nlscc** [comment]
Closing because I'm 99% sure that PHY is invalid and doesn't work with other tools. Feel free to reopen if you think otherwise.
