### ISSUE TITLE
"NoneType" object is not iterable

### ISSUE THREAD

**Issue by yalcinozer** [nlscc/samloader#50]
Hi, first of all, thanks for this tool. I downloaded a firmware successfully. But when I try to decrypt it, I get an error. I'm adding the error message.

`Traceback (most recent call last):
  File "C:\Users\realite-ins\AppData\Local\Programs\Python\Python39\Scripts\samloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('samloader==0.3', 'console_scripts', 'samloader')())
  File "c:\users\realite-ins\appdata\local\programs\python\python39\lib\site-packages\samloader\main.py", line 73, in main
    key = getkey(args.fw_ver, args.dev_model, args.dev_region)
  File "c:\users\realite-ins\appdata\local\programs\python\python39\lib\site-packages\samloader\crypt.py", line 27, in getv4key
    deckey = request.getlogiccheck(fwver, logicval)
  File "c:\users\realite-ins\appdata\local\programs\python\python39\lib\site-packages\samloader\request.py", line 13, in getlogiccheck
    for c in nonce:
TypeError: 'NoneType' object is not iterable`

**Comment by yalcinozer** [comment]
I tried it again today. It runs good. I don't know but I was doing wrong something I guess.
