### ISSUE TITLE
Exception: DownloadBinaryInform returned 400, firmware could not be found?

### ISSUE THREAD

**Issue by andrewchan0307** [nlscc/samloader#51]
## Description
I have successfully installed Python 3.9.6 and Samloader on my machine. Upon executing "checkupdate", Samloader does return the firmware version. However, when further executing the download command, it fails with "Exception: DownloadBinaryInform returned 200, firmware could not be found?" error. Full output below.

## Output
PS C:\Users\andre\Downloads> py -m samloader -m SM-A6060 -r TGY checkupdate
A6060ZHU3CUD5/A6060TGY3CUD5/A6060ZHU3CUD4/A6060ZHU3CUD5

PS C:\Users\andre\Downloads> py -m samloader -m SM-A6060 -r TGY download -v A6060ZHU3CUD5/A6060TGY3CUD5/A6060ZHU3CUD4/A6060ZHU3CUD5 -O .
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\samloader\__main__.py", line 6, in <module>
    main()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\samloader\main.py", line 37, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\samloader\main.py", line 89, in getbinaryfile
    raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
Exception: DownloadBinaryInform returned 400, firmware could not be found?

## Environment
Windows 10, and Python 3.9.6

**Comment by celsotavaresdev** [comment]
Same here (Fedora 34 and Python 3.9.6).
I'm trying to download the latest firmware for SM-A530F / ZTO (release date 08/14/2021):

$ python3 -m samloader -m SM-A530F -r ZTO checkupdate
`A530FXXSLCUG3/A530FOXMLCUG3/A530FXXSLCUG3/A530FXXSLCUG3`

---
$ python3 -m samloader -m SM-A530F -r ZTO download -v A530FXXSLCUG3/A530FOXMLCUG3/A530FXXSLCUG3/A530FXXSLCUG3 -O .
```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/celsotavares/.local/lib/python3.9/site-packages/samloader/__main__.py", line 6, in <module>
    main()
  File "/home/celsotavares/.local/lib/python3.9/site-packages/samloader/main.py", line 37, in main
    path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
  File "/home/celsotavares/.local/lib/python3.9/site-packages/samloader/main.py", line 89, in getbinaryfile
    raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
Exception: DownloadBinaryInform returned 400, firmware could not be found?
```

**Comment by TheAirBlow** [comment]
> Same here (Fedora 34 and Python 3.9.6). I'm trying to download the latest firmware for SM-A530F / ZTO (release date 08/14/2021):
> 
> ```
> $ python3 -m samloader -m SM-A530F -r ZTO checkupdate
> A530FXXSLCUG3/A530FOXMLCUG3/A530FXXSLCUG3/A530FXXSLCUG3
> 
> $ python3 -m samloader -m SM-A530F -r ZTO download -v A530FXXSLCUG3/A530FOXMLCUG3/A530FXXSLCUG3/A530FXXSLCUG3 -O .
> Traceback (most recent call last):
>   File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/celsotavares/.local/lib/python3.9/site-packages/samloader/__main__.py", line 6, in <module>
>     main()
>   File "/home/celsotavares/.local/lib/python3.9/site-packages/samloader/main.py", line 37, in main
>     path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
>   File "/home/celsotavares/.local/lib/python3.9/site-packages/samloader/main.py", line 89, in getbinaryfile
>     raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
> Exception: DownloadBinaryInform returned 400, firmware could not be found?
> ```

Same command works for me, so it was something temponary.
 Also, my tool [Syndical](https://github.com/theairblow/syndical) works faster for me for no apparent reason lol

**Comment by TheAirBlow** [comment]
> ## Description
> 
> I have successfully installed Python 3.9.6 and Samloader on my machine. Upon executing "checkupdate", Samloader does return the firmware version. However, when further executing the download command, it fails with "Exception: DownloadBinaryInform returned 200, firmware could not be found?" error. Full output below.
> ## Output
> 
> ```
> PS C:\Users\andre\Downloads> py -m samloader -m SM-A6060 -r TGY checkupdate
> A6060ZHU3CUD5/A6060TGY3CUD5/A6060ZHU3CUD4/A6060ZHU3CUD5
> 
> PS C:\Users\andre\Downloads> py -m samloader -m SM-A6060 -r TGY download -v A6060ZHU3CUD5/A6060TGY3CUD5/A6060ZHU3CUD4/A6060ZHU3CUD5 -O .
> Traceback (most recent call last):
>   File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\samloader\__main__.py", line 6, in <module>
>     main()
>   File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\samloader\main.py", line 37, in main
>     path, filename, size = getbinaryfile(client, args.fw_ver, args.dev_model, args.dev_region)
>   File "C:\Users\andre\AppData\Local\Programs\Python\Python39\lib\site-packages\samloader\main.py", line 89, in getbinaryfile
>     raise Exception("DownloadBinaryInform returned {}, firmware could not be found?".format(status))
> Exception: DownloadBinaryInform returned 400, firmware could not be found?
> ```
> 
> ## Environment
> 
> Windows 10, and Python 3.9.6

This one tho doesn't work for me, including my tool Syndical. 
It can't find the firmware that you specify. For example, latest firmware downloads fine.
Here are all available firmware versions: [link](https://fota-cloud-dn.ospserver.net/firmware/TGY/SM-A6060/version.xml)

**Comment by TheAirBlow** [comment]
```
Connecting to FUS server...
Unable to fetch firmware for A6060ZHU3CUD5/A6060TGY3CUD5/A6060ZHU3CUD4/A6060ZHU3CUD5  
┌─────────────────────────────────────────────────────────┬────────────────┬────────────┬────────┐
│ Version                                                 │ Android        │ Size       │ Latest │
├─────────────────────────────────────────────────────────┼────────────────┼────────────┼────────┤
│ A6060ZHU3CUJ1/A6060TGY3CUJ1/A6060ZHU3CUJ1/A6060ZHU3CUJ1 │ R(Android 11)  │ 4713480560 │ True   │
│ A6060ZHS2BTL1/A6060TGY2BTL1/A6060ZHS2BTL1/A6060ZHS2BTL1 │ Q(Android 10)  │ 4300965424 │ False  │
│ A6060ZHU3BUCA/A6060TGY3BUCA/A6060ZHU3BUCA/A6060ZHU3BUCA │ Q(Android 10)  │ 4713480560 │ False  │
│ A6060ZHU1ASL1/A6060TGY1ASL1/A6060ZHU1ASL1/A6060ZHU1ASL1 │ Pie(Android 9) │ 4300965424 │ False  │
│ A6060ZHU2BTJ2/A6060TGY2BTJ2/A6060ZHU2BTJ2/A6060ZHU2BTJ2 │ Q(Android 10)  │ 4300965424 │ False  │
│ A6060ZHU3CUD3/A6060TGY3CUD3/A6060ZHU3CUD2/A6060ZHU3CUD3 │ R(Android 11)  │ 4713480560 │ False  │
│ A6060ZHU3CUD5/A6060TGY3CUD5/A6060ZHU3CUD4/A6060ZHU3CUD5 │ /UNKNOWN/      │ 0          │ False  │
│ A6060ZHU1BTD3/A6060TGY1BTD3/A6060ZHU1BTD3/A6060ZHU1BTD3 │ Q(Android 10)  │ 4300965424 │ False  │
│ A6060ZHU1BTG1/A6060TGY1BTG1/A6060ZHU1BTG1/A6060ZHU1BTG1 │ Q(Android 10)  │ 4300965424 │ False  │
│ A6060ZHU1BTD1/A6060TGY1BTD1/A6060ZHU1BTD1/A6060ZHU1BTD1 │ Q(Android 10)  │ 4300965424 │ False  │
└─────────────────────────────────────────────────────────┴────────────────┴────────────┴────────┘
                                                                                      
Fetching firmware information ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 00:00:06  
                                                                                     
```

That version is the only that can't be fetched.

**Comment by hgerrald** [comment]
I'm experiencing the same issue for a few other firmwares. Checkupdate works but then download fails. Have any discoveries been made on this lately or any possible ideas causing the issue?

**Comment by yashikada** [comment]
I have the same issue and I don't have a solution, but I understand this: checkupdate don't return the latest version and version doesn't exist.
I checked with samfrew(DOT)com versions (latest and previous) for my device PDA/AP - CSC - MODEM/CP and I maked the parameter for -v "PDA/AP / CSC / MODEM/CP / PDA/AP" and I downloaded the encrypted firmware and decrypt works.

**Comment by yashikada** [comment]
I have found a solution, just apply this patch to samloader

```
diff --git a/samloader/main.py b/samloader/main.py
index eba0dc0..04b7ce0 100644
--- a/samloader/main.py
+++ b/samloader/main.py
@@ -26,6 +26,7 @@ def main():
     dload_out.add_argument("-O", "--out-dir", help="output the server filename to the specified directory")
     dload_out.add_argument("-o", "--out-file", help="output to the specified file")
     chkupd = subparsers.add_parser("checkupdate", help="check for the latest available firmware version")
+    chkupd.add_argument("-p", "--previous", help="previous version from xml", action="store_true")
     decrypt = subparsers.add_parser("decrypt", help="decrypt an encrypted firmware")
     decrypt.add_argument("-v", "--fw-ver", help="encrypted firmware version", required=True)
     decrypt.add_argument("-V", "--enc-ver", type=int, choices=[2, 4], default=4, help="encryption version (default 4)")
@@ -68,7 +69,7 @@ def main():
                     crypt.decrypt_progress(inf, outf, key, length)
             os.remove(out)
     elif args.command == "checkupdate":
-        print(versionfetch.getlatestver(args.dev_model, args.dev_region))
+        print(versionfetch.getver(args.dev_model, args.dev_region, not args.previous))
     elif args.command == "decrypt":
         getkey = crypt.getv4key if args.enc_ver == 4 else crypt.getv2key
         key = getkey(args.fw_ver, args.dev_model, args.dev_region)
diff --git a/samloader/versionfetch.py b/samloader/versionfetch.py
index 58ea186..cc42053 100644
--- a/samloader/versionfetch.py
+++ b/samloader/versionfetch.py
@@ -15,7 +15,7 @@ def normalizevercode(vercode: str) -> str:
         ver[2] = ver[0]
     return "/".join(ver)
 
-def getlatestver(model: str, region: str) -> str:
+def getver(model: str, region: str, latest: bool) -> str:
     """ Get the latest firmware version code for a model and region. """
     req = requests.get("https://fota-cloud-dn.ospserver.net/firmware/" \
         + region + "/" + model + "/version.xml")
@@ -23,7 +23,10 @@ def getlatestver(model: str, region: str) -> str:
         raise Exception("Model or region not found (403)")
     req.raise_for_status()
     root = ET.fromstring(req.text)
-    vercode = root.find("./firmware/version/latest").text
+    if latest:
+        vercode = root.find("./firmware/version/latest").text
+    else:
+        vercode = root.find("./firmware/version/upgrade/value").text
     if vercode is None:
         raise Exception("No latest firmware available")
     return normalizevercode(vercode)
```

and with checkupdate -p you got previous version and it can be used for get latest version.
This method is used by frija, it first check latest in version.xml and after first value from upgrade/value.
I will not make a PR because I see, mainteiner don't accept PR.

**Comment by Nemris** [comment]
@nlscc I did some experimenting, because both the `https://fota-cloud-dn.ospserver.net/firmware/<region>/<model>/version.xml` and samloader reported a firmware upgrade that samloader is apparently unable to fetch.

As it stands, neither Frija nor even Smart Switch are able to see this upgrade, contrarily to the OTA updater on the phone. This suggests that the "bug" isn't really a samloader issue, but rather a case of OTA upgrades possibly being stored in a different place and/or accessed in a different way than the known Smart Switch method.

Reverse engineering of `com.wssyncmldm` may yield more information, considering that the package actually appears to contain polling logic to determine whether an OTA upgrade is available.

**Comment by TheAirBlow** [comment]
> @nlscc I did some experimenting, because both the `https://fota-cloud-dn.ospserver.net/firmware/<region>/<model>/version.xml` and samloader reported a firmware upgrade that samloader is apparently unable to fetch.
> 
> As it stands, neither Frija nor even Smart Switch are able to see this upgrade, contrarily to the OTA updater on the phone. This suggests that the "bug" isn't really a samloader issue, but rather a case of OTA upgrades possibly being stored in a different place and/or accessed in a different way than the known Smart Switch method.
> 
> Reverse engineering of `com.wssyncmldm` may yield more information, considering that the package actually appears to contain polling logic to determine whether an OTA upgrade is available.

Probably not, because it is very unlikely that samsung adds more functionality than just downloading latest firmware. It is basically the same thing that Smart Switch does.

**Comment by Nemris** [comment]
> Probably not, because it is very unlikely that Samsung added more functionality than just downloading latest firmware. It is basically the same thing that Smart Switch does, so yeah.
> 
> Maybe they could have a library that is shared, and if it is it would be a jackpot.

Unfortunately, not even Smart Switch reports that an update is available - whereas the on-phone OTA updater finds one (and is able to download it), and the abovementioned URL agrees with it by reporting a firmware version neither Smart Switch nor samloader can fetch (or see, in Smart Switch's case).
