### ISSUE TITLE
Failed to decrypt

### ISSUE THREAD

**Issue by vmspike** [nlscc/samloader#60]
## Description

Failed to get `getv4key` because the response lacks the expected data.

## Reproduction Steps

```
$ samloader -m SM-G970F -r NZC download -v G970FXXSEFUL1/G970FOXMEFUJ2/G970FXXSEFUJ2/G970FXXSEFUL1 -O ./
$ samloader -m SM-G970F -r NZC decrypt -v G970FXXSEFUL1/G970FOXMEFUJ2/G970FXXSEFUJ2/G970FXXSEFUL1 -V 4 -i SM-G970F_3_20211201210000_1o2twxqmvg_fac.zip.enc4 -o SM-G970F_3_20211201210000_1o2twxqmvg_fac.zip.enc4
Traceback (most recent call last):
  File "/home/vmspike/.local/bin/samloader", line 11, in <module>
    load_entry_point('samloader==0.3', 'console_scripts', 'samloader')()
  File "/home/vmspike/.local/lib/python3.6/site-packages/samloader/main.py", line 73, in main
    key = getkey(args.fw_ver, args.dev_model, args.dev_region)
  File "/home/vmspike/.local/lib/python3.6/site-packages/samloader/crypt.py", line 25, in getv4key
    fwver = root.find("./FUSBody/Results/LATEST_FW_VERSION/Data").text
AttributeError: 'NoneType' object has no attribute 'text'
```

## Output

Adding req/response logging to `getv4key` function I got this:
req:
```
b'<FUSMsg><FUSHdr><ProtoVer>1.0</ProtoVer></FUSHdr><FUSBody><Put><ACCESS_MODE><Data>2</Data></ACCESS_MODE><BINARY_NATURE><Data>1</Data></BINARY_NATURE><CLIENT_PRODUCT><Data>Smart Switch</Data></CLIENT_PRODUCT><DEVICE_FW_VERSION><Data>G970FXXSEFUL1/G970FOXMEFUJ2/G970FXXSEFUJ2/G970FXXSEFUL1</Data></DEVICE_FW_VERSION><DEVICE_LOCAL_CODE><Data>NZC</Data></DEVICE_LOCAL_CODE><DEVICE_MODEL_NAME><Data>SM-G975F</Data></DEVICE_MODEL_NAME><LOGIC_CHECK><Data>GSF7F9EFEFXGUFLE</Data></LOGIC_CHECK></Put></FUSBody></FUSMsg>'
```
resp:
```
<?xml version="1.0" encoding="utf-8" ?>
<FUSMsg>
        <FUSHdr>
                <ProtoVer>1.0</ProtoVer>
                <SessionID></SessionID>
                <MsgID>1</MsgID>
        </FUSHdr>
        <FUSBody>
                <Results>
                        <CmdRef>2</CmdRef>
                        <Status>400</Status>
                </Results>
        </FUSBody>
</FUSMsg>
```
There is no expected value, that's why AttributeError is thrown.

## Environment

Ubuntu 18.04, Python 3.6.9, latest samloader from master

**Comment by vmspike** [comment]
Was my stupid mistake using incorrect dev model. Closing.
