### ISSUE TITLE
HTTPError: 403 Client Error

### ISSUE THREAD

**Issue by lenovolobo933** [nlscc/samloader#61]
python3 -m samloader -m SM-G906 -r THL checkupdate
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lenovo/.local/lib/python3.10/site-packages/samloader/__main__.py", line 6, in <module>
    main()
  File "/home/lenovo/.local/lib/python3.10/site-packages/samloader/main.py", line 70, in main
    print(versionfetch.getlatestver(args.dev_model, args.dev_region))
  File "/home/lenovo/.local/lib/python3.10/site-packages/samloader/versionfetch.py", line 22, in getlatestver
    req.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://fota-cloud-dn.ospserver.net/firmware/THL/SM-G906/version.xml

**Comment by nlscc** [comment]
this error is when the model name and/or region are not found. currently the tool passes through the error code from the server so it will show 403 BUT I am planning on adding better error messages for this later
